import { Agent, type Task } from "../core/agent";
import { askLlm } from "../llm/groq";
import * as git from "./git-tools";
import * as fs from "./fs-tools";
import * as pm2 from "./pm2-tools";
import { runBuildCheck } from "../safety/test-gate";
import fsModule from "fs";
import path from "path";

const PERSONA_PATH = path.join(process.cwd(), "agents", "hacker-context.md");

function loadPersona(): string {
  try {
    return fsModule.readFileSync(PERSONA_PATH, "utf-8");
  } catch {
    return "You are a senior software engineer maintaining the Kapster codebase.";
  }
}

export class HackerAgent extends Agent {
  constructor() {
    super("hacker");
  }

  async execute(taskId: string): Promise<string> {
    const task = await this.getTask(taskId);
    if (!task) throw new Error("Task not found");

    await this.updateTask(taskId, { status: "in_progress" } as Partial<Task>);
    await this.log({
      agent_id: "hacker",
      task_id: taskId,
      action: "task_started",
      details: { title: task.title },
    });

    try {
      const persona = loadPersona();
      const gitStatus = await git.getStatus();
      const pm2Status = await pm2.getStatus();
      const pm2Logs = await pm2.getLogs(20);

      const context = `Current git branch: ${gitStatus.branch}
Git has changes: ${gitStatus.hasChanges}
PM2 status: ${JSON.stringify(pm2Status)}
Recent PM2 logs: ${pm2Logs.slice(0, 1000)}

Task: ${task.title}
Description: ${task.description ?? "none"}

Generate a step-by-step plan and implement the fix. Return JSON:
{
  "plan": ["step1", "step2", ...],
  "files": ["file1.ts", "file2.ts", ...],
  "status": "done" | "failed" | "needs_help",
  "summary": "what was done"
}`;

      const response = await askLlm(
        [
          { role: "system", content: persona },
          { role: "user", content: context },
        ],
        { temperature: 0.2, maxTokens: 1500, responseFormat: "json" }
      );

      const result = JSON.parse(response);

      await this.log({
        agent_id: "hacker",
        task_id: taskId,
        action: "task_plan",
        details: { plan: result.plan, files: result.files },
      });

      if (result.status === "needs_help") {
        await this.updateTask(taskId, {
          status: "blocked",
          escalation: {
            reason: "Hacker cannot complete this task",
            what_i_need: result.summary ?? "See task description",
            requested_at: new Date().toISOString(),
          },
        } as Partial<Task>);

        return `BLOCKED: ${result.summary}`;
      }

      // Run build check
      const buildResult = await runBuildCheck();
      if (!buildResult.passed) {
        await this.updateTask(taskId, { status: "failed" } as Partial<Task>);
        await this.log({
          agent_id: "hacker",
          task_id: taskId,
          action: "build_failed",
          details: { output: buildResult.output.slice(0, 500) },
        });

        return `BUILD FAILED: ${buildResult.output.slice(0, 200)}`;
      }

      if (result.files?.length > 0) {
        const branchName = await git.createBranch(taskId, task.title);
        try {
          await git.commitAndPush(result.files, `feat(agent-hacker): ${task.title}`);
          await git.createPr(task.title, result.summary ?? "Auto-generated by Hacker agent");
        } catch {
          await git.cleanupBranch(branchName);
          throw new Error("Git operation failed");
        }
      }

      await this.updateTask(taskId, { status: "completed" } as Partial<Task>);
      await this.log({
        agent_id: "hacker",
        task_id: taskId,
        action: "task_completed",
        details: { summary: result.summary, files: result.files },
      });

      return `DONE: ${result.summary}`;
    } catch (error) {
      const msg = error instanceof Error ? error.message : String(error);
      await this.updateTask(taskId, { status: "failed" } as Partial<Task>);
      await this.log({
        agent_id: "hacker",
        task_id: taskId,
        action: "task_failed",
        details: { error: msg },
      });

      return `FAILED: ${msg}`;
    }
  }
}
