"use client";

import { useEffect, useRef } from "react";
import QRCode from "qrcode";

interface Props {
  url: string;
  name: string;
}

const QR_SIZE = 200;
const PADDING = 28;
const TITLE_H = 44;
const FOOTER_H = 32;
const W = QR_SIZE + PADDING * 2;
const H = TITLE_H + QR_SIZE + FOOTER_H;

function roundRect(
  ctx: CanvasRenderingContext2D,
  x: number,
  y: number,
  w: number,
  h: number,
  r: number
) {
  ctx.beginPath();
  ctx.moveTo(x + r, y);
  ctx.lineTo(x + w - r, y);
  ctx.quadraticCurveTo(x + w, y, x + w, y + r);
  ctx.lineTo(x + w, y + h - r);
  ctx.quadraticCurveTo(x + w, y + h, x + w - r, y + h);
  ctx.lineTo(x + r, y + h);
  ctx.quadraticCurveTo(x, y + h, x, y + h - r);
  ctx.lineTo(x, y + r);
  ctx.quadraticCurveTo(x, y, x + r, y);
  ctx.closePath();
}

export default function QrCodeWithFrame({ url, name }: Props) {
  const canvasRef = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    let cancelled = false;

    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    const dpr = window.devicePixelRatio || 1;

    canvas.width = W * dpr;
    canvas.height = H * dpr;
    ctx.scale(dpr, dpr);

    ctx.imageSmoothingEnabled = true;
    ctx.imageSmoothingQuality = "high";

    roundRect(ctx, 0, 0, W, H, 14);
    ctx.fillStyle = "#ffffff";
    ctx.fill();

    let displayName = name.trim() || "Barbershop";
    ctx.font = `bold 15px "Inter", sans-serif`;
    const maxW = W - 24;
    if (ctx.measureText(displayName).width > maxW) {
      while (
        ctx.measureText(displayName + "\u2026").width > maxW &&
        displayName.length > 1
      ) {
        displayName = displayName.slice(0, -1);
      }
      displayName += "\u2026";
    }
    ctx.fillStyle = "#1a1a1a";
    ctx.textAlign = "center";
    ctx.textBaseline = "middle";
    ctx.fillText(displayName, W / 2, TITLE_H / 2);

    const qrX = PADDING;
    const qrY = TITLE_H;

    QRCode.toDataURL(url, {
      width: QR_SIZE,
      margin: 0,
      color: { dark: "#1a1a1a", light: "#ffffff" },
    }).then((dataUrl) => {
      if (cancelled) return;
      const img = new Image();
      img.onload = () => {
        if (cancelled) return;
        ctx.drawImage(img, qrX, qrY, QR_SIZE, QR_SIZE);

        ctx.fillStyle = "#888888";
        ctx.font = '10px "Inter", sans-serif';
        ctx.textAlign = "center";
        ctx.textBaseline = "middle";
        ctx.fillText("Generated by kapster.my.id", W / 2, TITLE_H + QR_SIZE + FOOTER_H / 2);
      };
      img.src = dataUrl;
    });

    return () => {
      cancelled = true;
    };
  }, [url, name]);

  const download = () => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    const link = document.createElement("a");
    const safeName = name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/(^-|-$)/g, "")
      || "barbershop";
    link.download = `qrcode-${safeName}.png`;
    link.href = canvas.toDataURL("image/png");
    link.click();
  };

  return (
    <div className="flex flex-col items-center gap-4">
      <div className="bg-white rounded-2xl shadow-lg overflow-hidden">
        <canvas
          ref={canvasRef}
          style={{ width: W, height: H, display: "block" }}
          width={W}
          height={H}
        />
      </div>
      <button
        type="button"
        onClick={download}
        className="px-5 py-2.5 rounded-xl gold-gradient text-dark-900 font-bold text-sm cursor-pointer"
      >
        Download QR Code
      </button>
    </div>
  );
}
